export const NO_ADDR_RESOLUTION_SET = 'KB001: No addr resolution set';
export const NO_ADDR_RESOLUTION = 'KB002: No addr resolution';
export const NO_RESOLVER = 'KB003: No resolver';
export const LIBRARY_NOT_COMPOSED = 'KB004: Library not composed';
export const NO_ADDRESSES_PROVIDED = 'KB005: No contract addresses provided';
export const NO_CHAIN_ADDR_RESOLUTION = 'KB006: No chain address resolution';
export const NO_CHAIN_ADDR_RESOLUTION_SET = 'KB007: No chain address resolution set';
export const SEARCH_ONLY_SIMPLE_DOMAINS = 'KB008: Search only domains';
export const SEARCH_DOMAINS_UNDER_AVAILABLE_TLDS = 'KB009: Search only .rsk domains';
export const INVALID_DOMAIN = 'KB010: Invalid domain, must be alphanumeric and lower case';
export const INVALID_LABEL = 'KB011: Invalid label, must be alphanumeric and lower case';
export const DOMAIN_NOT_EXISTS = 'KB012: The given domain does not exist';
export const NO_NAME_RESOLUTION = 'KB013: No name resolution';
export const NO_REVERSE_RESOLUTION_SET = 'KB014: No reverse resolution set'
